### ISSUE TITLE
Paragraph tags in list items don't work

### ISSUE THREAD

**Issue by kiranshila** [dracula/dracula-ui#109]
As per the HTML spec, blocks *should* work in list items. It seems something like [this StackOverflow issue](https://stackoverflow.com/questions/45462642/handling-paragraphs-inside-list-items-with-a-custom-css-content) might be the problem.

### Example
```html
<div class="drac-box">
	<ul class="drac-list drac-list-unordered drac-list-purple">
    	<li class="drac-text drac-text-white">
			<p class="drac-text drac-line-height drac-text-cyan">Foo</p>
 		</li>
    	<li class="drac-text drac-text-white">
			<p class="drac-text drac-line-height drac-text-green">Bar</p>
 		</li>
	</ul>
</div>
```
![image](https://user-images.githubusercontent.com/6305359/121440558-1c0e4600-c956-11eb-861e-6abce17240cf.png)

**Comment by leandrocunha** [comment]
Hi @kiranshila and @LucianoLaratelli ,
I can understand that it isn't a bug, once the use of a block element into a non-block element doesn't change the behavior natively. Dracula UI provides a list of utility classes that you can use in these cases. For example, if you add the `drac-d-inline-block` in your <p> element you will reach the result you want as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/1820920/194526418-51d36956-1662-4d48-af66-4db0b11ac4cb.png)

![image](https://user-images.githubusercontent.com/1820920/194526503-9bb3aed9-fb29-49ef-9a86-853fad349302.png)

cc @luxonauta

**Comment by luxonauta** [comment]
Hi 🙋🏻‍♂️, as Leandro said, this behaviour is not a 🐛; doing as he shows in the example should solve these problems you faced so that I will close this Issue.
