### ISSUE TITLE
License/Usage Question: Open Source Software

### ISSUE THREAD

**Issue by Apollorion** [dracula/dracula-ui#125]
I want to use dracula ui in an [open source project I have](https://github.com/apollorion/manifests.io), reading over the [license it seems like thats allowed](https://github.com/dracula/dracula-ui/blob/master/LICENSE.md?plain=1#L23). What is the recommended way of using dracula ui in an open source project that would allow other developers to clone and run the project themselves without having to purchase dracula ui? ~Should I copy dracula ui source directly into the project?~ [It appears this isnt allowed either?](https://github.com/dracula/dracula-ui/blob/master/LICENSE.md?plain=1#L29) How should I distribute my code in a way that uses dracula ui?

**Comment by zenorocha** [comment]
@Apollorion the repository is now open source under the MIT license.
