### ISSUE TITLE
Add tailwind style via className make component style disappear

### ISSUE THREAD

**Issue by peguimasid** [dracula/dracula-ui#135]
# Here is an example of what i like to say

![Captura de Tela 2022-10-01 às 12 31 28 PM](https://user-images.githubusercontent.com/54289589/193416976-f0d63ec1-8ee8-4fbd-9277-de7935bef001.png)
and adding `className`:
![Captura de Tela 2022-10-01 às 12 32 02 PM](https://user-images.githubusercontent.com/54289589/193416986-c88f9fea-e37a-4b14-b07c-e4e33d4c2877.png)

I don't know if i made some config wrong, it is an error or is not supported.

Im using Next.js with tailwind-dracula and draculaUI and follow [this instructions](https://ui.draculatheme.com/installation)

File: `tailwind.config.js`
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('tailwind-dracula')('dracula', true)],
};
```

**Comment by luxonauta** [comment]
Hi Guilhermo, is this still a problem? 🤔

And if you try to avoid using className as a prop. 💪🏻 That way, it might be harder for you to know your component's state. You could add an extra class, which you can easily extend.

You would need a helper to match class name strings conditionally.
