### ISSUE TITLE
Version 1.0.4 causes "Module not found: Error: Can't resolve 'dracula-ui/styles/dracula-ui.css'"

### ISSUE THREAD

**Issue by syeo66** [dracula/dracula-ui#152]
When using dracula-ui with npm in a react project I got

"Module not found: Error: Can't resolve 'dracula-ui/styles/dracula-ui.css'" after updating to 1.0.4. Going back to 1.0.3 resolved it.

Am importing it with
```
import 'dracula-ui/styles/dracula-ui.css'
import { ... } from 'dracula-ui'
```

as stated in https://ui.draculatheme.com/installation

**Comment by luxonauta** [comment]
⚠️ I'm investigating what's causing this; in the meantime, I'll regenerate the build and publish a new version.

**Comment by syeo66** [comment]
Just tested with 1.0.5. Problem persists.
![Bildschirmfoto von 2023-01-24 15-40-20](https://user-images.githubusercontent.com/1178021/214324188-b130ddd3-41d7-4b2f-a40b-e894ca622085.png)

**Comment by vouneo** [comment]
I think I have a similar problem. I tried using react and didn't work, then I tried using plaing HTML with the link provided by the Dracula docs ` npm install dracula-ui

<link rel="stylesheet" href="node_modules/dracula-ui/styles/dracula-ui.css" />` 
But if search in node modules the "dracula-ui.css" is not there. 
Changing the path didn't work either just the CDN is now functioning.

**Comment by Subtixx** [comment]
1.0.4 and 1.0.5 are completely broken.

**Comment by luxonauta** [comment]
The issue is now resolved, and you can use the latest published version, v1.0.6!

What happened was that I made some mistakes that caused versions v1.0.4 and v1.0.5 not correctly to distribute the compiled version of the project.

**Comment by vouneo** [comment]
Great, thank you! I'm gonna try it right now.

**Comment by syeo66** [comment]
Can confirm: works again. Thank you very much!
