### ISSUE TITLE
Tailwind Version of Dracula UI

### ISSUE THREAD

**Issue by pbteja1998** [dracula/dracula-ui#78]
I would love if there is some sort of a Tailwind compatible version of Dracula UI — so that it would be possible to do things like `sm:drac-text-sm lg:drac-text-lg` among other things.

Ideally, it should be like adding some custom config to `tailwind.config.js`, which would auto generate all the `drac-*` classes.

I would also try to come up with something similar to this, I think this is straightforward to achieve for every type of class other than those with gradients. Would have to do some hacking for gradients to work with Tailwind.

**Comment by luxonauta** [comment]
🎃 It's not in the plans; Since you can already use both, especially Dracula UI, side by side with Tailwind CSS without any problems. This is an option if the person wants to use Tailwind with Dracula without using the UI.
